### ISSUE TITLE
Email Vector

### ISSUE THREAD

**Issue by andersthemagi** [andersthemagi/ai-scam-detection#2]
# Email
- User receives an email from a source that is outside of their organization, or potentially scammy. For the demo, it can be a pre-defined string. 
- The model parses the email content for emails, links, verbiage, attachments, that might be a scam. Cross reference sources like [Scamsearch](https://scamsearch.io/) to determine whether it is a reported scam
- The user receives feedback on whether or not it is a scam

## Deliverable

- Using `email.py`, produce a webpage on Streamlit that showcases functionality. https://docs.streamlit.io/develop/tutorials/llms/build-conversational-apps has info on where to start, and the documentation is extremely easy to parse through. 
https://github.com/andersthemagi/general-pervasive also has examples of how I've implemented something like this in the past.

**Comment by andersthemagi** [comment]
![image](https://github.com/user-attachments/assets/733496cc-f4a5-4b38-84fb-7b0b96c05579)

**Comment by CodingEloise** [comment]
I’d like to work on this:)

**Comment by Eloisezh** [comment]
![image](https://github.com/user-attachments/assets/e37881d8-b5c2-475f-8b43-ff08dd5518cf)
