### ISSUE TITLE
Audio Vector

### ISSUE THREAD

**Issue by andersthemagi** [andersthemagi/ai-scam-detection#3]
As for the audio vector, that's tough. A lot of the audio parsing for potential deepfakes are proprietary or paywalled from my  research. Unless you want to use something like power automate and have the system "manually" upload an audio file for parsing. I think a long-term solution would pay for one of those APIs. 

A point of research and exploration might be determining whether turning "speech to text" into text and having the model parse it for potential scams would be viable. Are there quirks about how these deepfakes talk or artifacts in the transcript that can help identify these issues? Needs exploring this weekend, so if anybody feels emboldened to try that out, feel free to claim that.

## Deliverable

- Using `audio.py`, build a page on Streamlit that showcases this functionality. https://docs.streamlit.io/develop/tutorials/llms/build-conversational-apps as a documentation example. 
- https://github.com/andersthemagi/general-pervasive also has examples of how I've implemented something like this in the past.

**Comment by andersthemagi** [comment]
Some more thoughts on this one: 

https://github.com/andersthemagi/general-pervasive/blob/main/pages/audio.py shows how I've handled it in the past to ***generate*** audio, so I imagine the reverse can be done with OpenAI. https://platform.openai.com/docs/api-reference/audio/createTranscription

Evaluated a couple different API solutions that could help with this natively, however for the hackathon very likely out of scope:
- Hive: https://docs.thehive.ai/docs/ai-generated-audio-detection
- Resemble: https://www.resemble.ai/detect/

https://play.ht/voice-classifier-detect-ai-voices/ has a tool that could help illustrate this, albeit super manually.

**Comment by andersthemagi** [comment]
@ph0429 audio functionality should be live shortly, it's a bit of a simple demo but it should do for the hackathon. let me know if any changes should be made!

**Comment by ph0429** [comment]
for my own future reference: https://ai-scam-detection.streamlit.app/
@andersthemagi I see this error page now?
![Uploading Screenshot 2024-09-01 at 16.05.53.png…]()

**Comment by andersthemagi** [comment]
OpenAI for some reason didn't stick in the dependencies. Pushing a quick update now.

**Comment by andersthemagi** [comment]
https://github.com/andersthemagi/ai-scam-detection/commit/2023cce2bf555d530ec9d9261c1409903d715021

**Comment by andersthemagi** [comment]
@ph0429 Thanks for the heads up. some issues between the streamlit cloud and our repo that I just had to fix. Could you go ahead and take a look now? I think it's working on my end.

**Comment by ph0429** [comment]
@andersthemagi tested, this works!
