### ISSUE TITLE
AI-generated Proactive scam simulation and education

### ISSUE THREAD

**Issue by andersthemagi** [andersthemagi/ai-scam-detection#5]
Users lack experience in identifying scams. The solution will offer AI-generated, personalised scam simulations to educate users on recognizing and responding to potential threats.

## Deliverable

- Build a page on the app that acts as a "personalized AI scam simulation" or education on common scams

**Comment by andersthemagi** [comment]
![image](https://github.com/user-attachments/assets/1c65fc5a-d1be-441c-9926-ace345578357)

Super rudimentary mock-up of what I envision for this part of the app.

**Comment by ph0429** [comment]
@andersthemagi I hadn't thought about that format. 
My MVP idea for this feature was actually just a message that we create and then quiz the user as to whether the message is a scam or not. The message could use text from actual scam messages or scenarios to better simulate. 
If the message is a scam then we would educate the user as to the type of scam

**Comment by andersthemagi** [comment]
That could work! I can get a set of like maybe 10 sample texts and emails and create kind of like a quiz for it for now.

**Comment by andersthemagi** [comment]
Decided on just five for the demo, but these should help illustrate how we can educate our users with real examples.

**Comment by andersthemagi** [comment]
dunno why that closed. Keeping this task open for now in case any feedback and changes come through before we submit

**Comment by ph0429** [comment]
Cool! I see the examples on https://ai-scam-detection.streamlit.app/
That all works for now @andersthemagi , thanks for quickly creating these 🚀

**Comment by ph0429** [comment]
@andersthemagi FYI not reopening this task because I assume low priority - I see the explanation text in this section.
Suggestion to include explanation text similiar to what we see on the Audio section (which looks like text coming from OpenAI)
Only if we have completed everything and we're twiddling our thumbs, perhaps a small change to make
